/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package config;

/**
 *
 * @author lg
 */
public class ConfigSettingsPanel extends javax.swing.JPanel {

	/**
	 * Creates new form ConfigSettingsPanel
	 */
	public ConfigSettingsPanel () {
		initComponents ();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    companyLabel = new javax.swing.JLabel();
    codebiniLabel = new javax.swing.JLabel();
    empresa = new javax.swing.JTextField();
    codebinUrl = new javax.swing.JTextField();
    credentialsPanel = new config.CredentialsPanel();

    setLayout(new java.awt.GridBagLayout());

    companyLabel.setText("Empresa:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    add(companyLabel, gridBagConstraints);

    codebiniLabel.setText("Codebin URL:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    add(codebiniLabel, gridBagConstraints);

    empresa.setMinimumSize(new java.awt.Dimension(150, 27));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 137;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    add(empresa, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 137;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    add(codebinUrl, gridBagConstraints);

    credentialsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 14;
    gridBagConstraints.gridheight = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    add(credentialsPanel, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField codebinUrl;
  private javax.swing.JLabel codebiniLabel;
  private javax.swing.JLabel companyLabel;
  private config.CredentialsPanel credentialsPanel;
  private javax.swing.JTextField empresa;
  // End of variables declaration//GEN-END:variables
}
