package config;

public class CredentialsPanel extends javax.swing.JPanel {

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    credentialsTabsPanel = new javax.swing.JTabbedPane();
    colombiaTabPanel = new javax.swing.JPanel();
    colombiaPanel = new config.UserPasswordPanel();
    ecuadorTabPanel = new javax.swing.JPanel();
    ecuadorPanel = new config.UserPasswordPanel();
    peruTabPanel = new javax.swing.JPanel();
    peruPanel = new config.UserPasswordPanel();

    setLayout(new java.awt.BorderLayout());

    credentialsTabsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    colombiaTabPanel.add(colombiaPanel);

    credentialsTabsPanel.addTab("Colombia", colombiaTabPanel);

    ecuadorTabPanel.setLayout(new java.awt.BorderLayout());
    ecuadorTabPanel.add(ecuadorPanel, java.awt.BorderLayout.CENTER);

    credentialsTabsPanel.addTab("Ecuador", ecuadorTabPanel);

    peruTabPanel.setLayout(new java.awt.BorderLayout());
    peruTabPanel.add(peruPanel, java.awt.BorderLayout.CENTER);

    credentialsTabsPanel.addTab("Perú", peruTabPanel);

    add(credentialsTabsPanel, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private config.UserPasswordPanel colombiaPanel;
  private javax.swing.JPanel colombiaTabPanel;
  private javax.swing.JTabbedPane credentialsTabsPanel;
  private config.UserPasswordPanel ecuadorPanel;
  private javax.swing.JPanel ecuadorTabPanel;
  private config.UserPasswordPanel peruPanel;
  private javax.swing.JPanel peruTabPanel;
  // End of variables declaration//GEN-END:variables

	public CredentialsPanel () {
		initComponents ();
	}

	public String getUserColombia () {
		return (this.colombiaPanel.getUser ());
	}

	public String getPasswordColombia () {
		return (this.colombiaPanel.getPassword ());
	}

	public String getUserEcuador () {
		return (this.ecuadorPanel.getUser ());
	}

	public String getPasswordEcuador () {
		return (this.ecuadorPanel.getPassword ());
	}

	public String getUserPeru () {
		return (this.peruPanel.getUser ());
	}

	public String getPasswordPeru () {
		return (this.peruPanel.getPassword ());
	}

	public void setUserColombia (String user) {
		this.colombiaPanel.setUser (user);
	}

	public void setPasswordColombia (String password) {
		this.colombiaPanel.setPassword (password);
	}

	public void setUserEcuador (String user) {
		this.ecuadorPanel.setUser (user);
	}

	public void setPasswordEcuador (String password) {
		this.ecuadorPanel.setPassword (password);
	}

	public void setUserPeru (String user) {
		this.peruPanel.setUser (user);
	}

	public void setPasswordPeru (String password) {
		this.peruPanel.setPassword (password);
	}
}
